# Standalone BGV benchmark binary.
cc_binary(
    name = "bgv_bench",
    srcs = ["bgv_bench.cpp"],
    deps = [
        "@heir//scheme-test/bench",
        "@openfhe//:core",
        "@openfhe//:pke",
    ],
)

cc_binary(
    name = "ckks_bench",
    srcs = ["ckks_bench.cpp"],
    deps = [
        "@heir//scheme-test/bench",
        "@openfhe//:core",
        "@openfhe//:pke",
    ],
)

cc_binary(
    name = "ckks_bootstrap_bench",
    srcs = ["ckks_bootstrap_bench.cpp"],
    deps = [
        "@heir//scheme-test/bench",
        "@openfhe//:core",
        "@openfhe//:pke",
    ],
)
