# Standalone BGV benchmark binary.
cc_binary(
    name = "bgv_bench",
    srcs = ["bgv_bench.cpp"],
    deps = [
        "@heir//scheme-test/bench",
        "@openfhe//:pke",
        "@openfhe//:core",
    ],
)